const information ={
    list :[
        {
            id:"List_1",
            name:"必填信息",
            open:false,
            page:"./user_resume_info_must_p/user_resume_info_must_p"
        },
        {
            id:"List_2",
            name:"教育经历",
            open:false,
            page:"./edu_exp_p/edu_exp_p"
        },
        {
            id:"List_3",
            name:"实习工作",
            open:false,
            page:"./internship_exp_p/internship_exp_p"
        },
        {
            id:"List_4",
            name:"项目经历",
            open:false,
            page:"./project_exp_p/project_exp_p"
        },
        {
            id:"List_5",
            name:"奖励信息",
            open:false,
            page:"./award_info_p/award_info_p"
        },
        {
            id:"List_6",
            name:"技能爱好",
            open:false,
            page:"./skill_info_p/skill_info_p"
        },
        {
            id:"List_7",
            name:"自我评价",
            open:false,
            page:"./self_assessment_p/self_assessment_p"
        },
        {
            id:"List_8",
            name:"其他信息",
            open:false,
            page:"./other_info_p/other_info_p"
        },
    ],
};
module.exports = information;